resource_group_name         = "archi-main"
location                    = "switzerlandnorth"
backend_rg_name             = "archi-main-backend"
backend_sa_name             = "archimainbackend"
backend_container_name      = "archiecontmain"